version: "3.3"

#====================#
#      Services      #
#====================#
services:

  #=====================#
  #       Grafana       #
  #=====================#
  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.3
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - grafanaData:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  #=====================#
  #       Influx       #
  #=====================#
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxData:/var/lib/influxdb2
      - ./influx/config.yml:/etc/influxdb2/config.yml

  #=====================#
  #       Telegraf       #
  #=====================#
  telegraf:
    container_name: telegraf
    image: telegraf:1.29.5
    restart: unless-stopped
    ports:
      - "8092:8092"
      - "8094:8094"
      - "8125:8125"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb

  #=================================#
  #      Mosquitto MQTT Broker      #
  #=================================#
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18
    restart: unless-stopped
    ports:
      - "8883:1883"
    volumes:
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  #=================================#
  #            Node Red             #
  #=================================#
  nodered:
    container_name: nodered
    build: ./nodered
    image: nodered/node-red:3.1
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - noderedData:/data
      - ./nodered/defaultFlows:/data/lib/flows


#====================#
#      Volumnes      #
#====================#
volumes:
  grafanaData:
  noderedData:
  mosquittoLog:
  mosquittoData:
  influxData:

